title: Maxwell Irowa
#logo: /assets/img/headshot_circle.png
#description: Computer Information Systems Student | Data Analyst Enthusiast | Aspiring Software Engineer
#show_downloads: true
theme: jekyll-theme-minimal
